version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch-dependencies:
        update-types:
          - "minor"
          - "patch"
    target-branch: "main"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch-dependencies:
        update-types:
          - "minor"
          - "patch"
    target-branch: "baseline"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "baseline"
